version: '3'

services:
  api:
    container_name: ctnr-movie-api
    build: .
    command: npm run dev
    working_dir: /usr/src/movie-api
    restart: always
    volumes:
      - .:/usr/src/movie-api
      - ./package.json:/usr/src/movie-api/package.json
    ports:
      - "3000:3000"